[tox]
envlist =
    py310-pd21-dask
    py310-pd22-dask

    py311-pd21-dask
    py311-pd22-dask
    py311-pd23-dask

    py312-pd21-dask
    py312-pd22-dask
    py312-pd23-dask

    py313-pd22-dask
    py313-pd23-dask

[testenv]
commands =
  python -m pytest {posargs: tests}
deps =
    pytest
    pd21: pandas>=2.1,<2.2
    pd22: pandas>=2.2,<2.3
    pd23: pandas>=2.3,<2.4
    dask: dask[dataframe]
