# This file is based on example codes from https://github.com/actions/setup-python (released under the MIT license).
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - name: py38-pd13
            python: '3.8'
          - name: py311-pd20
            python: '3.11'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: |
          pip install -U pip
          pip install tox

      - name: Run tox
        run: tox -e ${{ matrix.name }}
