# This file is based on example codes from https://github.com/actions/setup-python (released under the MIT license).
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Pandas >= 1.2 requires Python >= 3.7
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        pandas-version: ["1.0", "1.1", "1.2", "1.3"]
        exclude:
          - pandas-version: "1.2"
            python-version: "3.6"
          - pandas-version: "1.3"
            python-version: "3.6"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry and requirements
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          # Remove poetry.lock to allow installing different versions of pandas
          rm poetry.lock
          poetry install --no-root

      - name: Install specified pandas version
        run: |
          pip install "pandas==${{ matrix.pandas-version }}.*"

      - name: Run unit tests
        run: |
          pytest tests/
